<?php
/**
 * Copyright © Pankaj Sharma. All rights reserved.
 */

/** @var $block \Pankaj\LogViewer\Block\Adminhtml\Log\View */
/** @var \Magento\Framework\Escaper $escaper */

$content = $block->getLogContent();
$fileName = $block->getLogFileName();
?>

<div class="page-main-actions log-viewer-toolbar">
    <div class="toolbar">
        <button onclick="window.location.href='<?= $escaper->escapeJs($escaper->escapeUrl($block->getBackUrl())) ?>'" 
                class="action-default scalable back"
                type="button">
            <span><?= $escaper->escapeHtml(__('Back to Logs List')) ?></span>
        </button>
    </div>
</div>

<div class="log-container-card">
    <div class="log-header">
        <?= $escaper->escapeHtml(__('Viewing Log:')) ?> 
        <span class="file-name"><?= $escaper->escapeHtml($fileName) ?></span>
    </div>
    <div class="log-body">
        <pre><?= $escaper->escapeHtml($content) ?></pre>
    </div>
</div>